baseURL = "/"
languageCode = "en-us"
title = "Roman Peshkov"
theme = "rp"
pluralizelisttitles = false
# pygmentsUseClassic=true
pygmentsStyle="monokai"
pygmentsCodeFences = true

[params]
recentCount = 3
avatar = "/avatar.jpg"
description = "developer, geek, workaholic"
copyright = "Copyright &copy; 2018 Roman Peshkov"

[params.social]
github = "rpeshkov"
linkedin = "rpeshkov"
twitter = "rpeshkov"
vk = "rpeshkov"
email = "peshkovroman@gmail.com"

[related]
threshold = 80 # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
includeNewer = true # To get stable "See also" sections we, by default, exclude newer related pages.
toLower = false # Will lower case keywords in both queries and in the indexes.

[[related.indices]]
name  = "tags"
weight = 100

[menu]
    [[menu.main]]
        name = "Blog"
        weight = 100
        identifier = "blog"
        url = "/blog/"
    [[menu.main]]
        name = "Links"
        identifier = "links"
        weight = 200
        url = "/links/"
